name: Ghcr.io Cleanup Action

description: >
  Delete untagged/tagged images from the GitHub Container Registry. Supports
  multi architecture and attestation images.

author: Dataaxiom Inc

branding:
  icon: trash-2
  color: blue

inputs:
  # General Settings
  token:
    description: >
      Token to authenticate with the ghcr.io registry and the GitHub API
    required: true

  owner:
    description: >
      Owner of the package (user or organization). Defaults to project owner
    required: false

  repository:
    description: >
      The GitHub repository where the package is stored. Defaults to repository
      name
    required: false

  package:
    description: >
      The package name. Defaults to the repository name
    required: false

  log-level:
    description: >
      Log level (error/warn/info/debug)
    required: false
    default: warn

  # Clean-up Options

  delete-tags:
    description: >
      Comma separated list of tags to delete. Suports wildcard syntax. Can be
      abbreviated as `tags`
    required: false

  tags:
    description: >
      Short form of `delete-tags` input option
    required: false

  exclude-tags:
    description: >
      Commma separated list of tags strictly to be preserved / excluded from
      deletion. Suports wildcard syntax
    required: false

  keep-n-untagged:
    description: >
      Number of untagged images to keep (sorted by date)
    required: false

  keep-n-tagged:
    description: >
      Number of tagged images to keep (sorted by date)
    required: false

  delete-untagged:
    description: >
      Delete untagged images (not belonging to multi architectrue images).
      Default option which is set to true when no other options set (true/false)
    required: false

  delete-ghost-images:
    description: >
      Delete multi architecture images where all underlying platform images are
      missing (true/false)
    required: false
    default: false

  delete-partial-images:
    description: >
      Delete multi architecture images where some (but not all) underlying
      platform images are missing (true/false)
    required: false
    default: false

  older-than:
    description: >
      Only include packages to be processed that are older than this value. Use
      the following format samples: 50 seconds, 15 days, 6 months, 2 years
    required: false

  validate:
    description: >
      Validate all multi architecture images manifests by checking their digests
      are present in the registry
    required: false

  dry-run:
    description: >
      Simulate action - does not remove any packages
    required: false

  log-level:
    description: >
      Log level (error/warn/info/debug)
    required: false

runs:
  using: node20
  main: dist/index.js
